#!/bin/sh

# Set these paths appropriately

TREETAGGER=res/ner/treetagger
BIN=$TREETAGGER/bin
CMD=$TREETAGGER/cmd
LIB=$TREETAGGER/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/polish-abbreviations-utf8
PARFILE=${LIB}/polish-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
