#!/bin/sh

# Set these paths appropriately

TREETAGGER=res/ner/treetagger
BIN=$TREETAGGER/bin
CMD=$TREETAGGER/cmd
LIB=$TREETAGGER/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
