#!/bin/sh

# Set these paths appropriately

TREETAGGER=res/ner/treetagger
BIN=$TREETAGGER/bin
CMD=$TREETAGGER/cmd
LIB=$TREETAGGER/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
